### ISSUE TITLE
参加したいとおもった人の連絡先をとっておきたい

### ISSUE THREAD

**Issue by so1** [johokaigi/johokaigi#38]
次のイベント申し込みがいまできないので
https://goo.gl/mOuwJ8
このフォームに誘導したい

**Comment by htomine** [comment]
top の Peatix の embedを差し替えればいいとコニーから。
#4募集としていいものかちょっとなやｍ．

**Comment by so1** [comment]
日時決まってないから募集ではなくて、Waiting Listでいいのでは

**Comment by htomine** [comment]
確かに :+1:

**Comment by htomine** [comment]
次のイベントがないときはトップページに出すようにしました。
