### ISSUE TITLE
repositoryのオーナー変更にtravisの設定が追従できていない

### ISSUE THREAD

**Issue by konishi** [johokaigi/johokaigi#54]

**Comment by htomine** [comment]
Gtihub側ではJohoKaigiにもアクセスできるとなっているけど
![image](https://cloud.githubusercontent.com/assets/732828/11318584/f18db7ba-909b-11e5-8189-4f1aeec75bba.png)

Travis側でOrganizationにJohoKaigiが出てこない
![image](https://cloud.githubusercontent.com/assets/732828/11318588/fb2efe1e-909b-11e5-9c54-1e80ef751f66.png)

**Comment by konishi** [comment]
https://travis-ci.org/johokaigi/johokaigi ここ見えるようになってません？

**Comment by htomine** [comment]
見えますね、もうできてたのか :pray:

**Comment by konishi** [comment]
設定完了&デプロイできてたのでcloseします〜
