### ISSUE TITLE
readme.mdの内容を自動でページに反映できたら最高

### ISSUE THREAD

**Issue by so1** [johokaigi/johokaigi#61]
https://github.com/johokaigi/johokaigi_staff/blob/master/README.md

お手伝いしてくれる人向けドキュメントのルートを
johokaigi_staffのREADME.mdにおくことにしたので、
それが、情報会議のウェブサイトにもはいっているとうれしい

**Comment by konishi** [comment]
できそう

**Comment by so1** [comment]
ありがとうございました！
