### ISSUE TITLE
masterブランチ以外での変更まで勝手にdeployされてしまっている

### ISSUE THREAD

**Issue by konishi** [johokaigi/johokaigi#68]
途中でownershipを変更したときにおかしくなった？

**Comment by konishi** [comment]
@htomine すいません http://qiita.com/kimihito_/items/54467c0333ee4964562d#%E3%82%84%E3%81%A3%E3%81%9F%E3%81%93%E3%81%A8 この設定作業をもう一度やってみてもらえませんか？ :bow:

**Comment by htomine** [comment]
@konycc :ok_woman: やってみます

**Comment by htomine** [comment]
https://github.com/johokaigi/johokaigi/commit/0ae84256b263fb76ec3ffea8bb20cbaf4ae0f552

**Comment by htomine** [comment]
@konycc ^ この箇所が変わるだけという感じでしたが、これでよさそう？

**Comment by konishi** [comment]
@htomine おそらく…？

**Comment by konishi** [comment]
直ってなかった…

**Comment by htomine** [comment]
変更取り込んだのmasterだからとか…？

**Comment by htomine** [comment]
@konycc ↓これの `Build pull requests` はいるやつですよねー。

![image](https://cloud.githubusercontent.com/assets/732828/11618012/dda02622-9cd8-11e5-8446-d5c2dea4a576.png)

**Comment by konishi** [comment]
@htomine masterにrebaseした後でもだめでした。いまbuild pull requestsためしにoffにしてみました！

**Comment by htomine** [comment]
>  masterにrebaseした後でもだめ

なるほど :sob:

**Comment by konishi** [comment]
offにしたらbuildはされなくなったかも？でもmasterにマージした時にどうなるか(この時もbuildされない可能性はある)

**Comment by htomine** [comment]
> でもmasterにマージした時にどうなるか

`Build pushes` でなんとかなってほしい :pray:

**Comment by htomine** [comment]
master へは mergeか…

**Comment by konishi** [comment]
offにしたら直ったようなのでcloseします。
